export CUDA_VISIBLE_DEVICES=2

python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/SMD \
  --model_id SMD \
  --model ISTAD \
  --data SMD \
  --features M \
  --seq_len 96 \
  --enc_in 38 \
  --c_out 38 \
  --istad_recon_type kanad \
  --istad_branch_mode hgat_kan_tcn \
  --istad_kan_grid_size 10 \
  --istad_kan_spline_order 3 \
  --istad_revin 1 \
  --use_bestf1_threshold 1 \
  --bestf1_search_mode adaptive \
  --bestf1_coarse_step_num 200 \
  --bestf1_fine_step_num 500 \
  --bestf1_use_adjustment 1 \
  --istad_dropout 0.2 \
  --istad_kanad_order 4 \
  --anomaly_ratio 1 \
  --learning_rate 0.01 \
  --batch_size 64 \
  --num_workers 4 \
  --patience 5 \
  --train_epochs 100 \
  --seed 2022 \
  --des SMD_revin_s2022
